# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import processed_datas_pb2 as processed_datas__pb2


class ProcessedDatasStub(object):
    """------------------------------
    Servicios
    ------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CrearProcessedImage = channel.unary_unary(
                '/processed_datas.ProcessedDatas/CrearProcessedImage',
                request_serializer=processed_datas__pb2.ProcessedImage.SerializeToString,
                response_deserializer=processed_datas__pb2.RespuestaProcessedImage.FromString,
                )
        self.ConsultarProcessedImage = channel.unary_unary(
                '/processed_datas.ProcessedDatas/ConsultarProcessedImage',
                request_serializer=processed_datas__pb2.QueryProcessedImage.SerializeToString,
                response_deserializer=processed_datas__pb2.RespuestaProcessedImage.FromString,
                )


class ProcessedDatasServicer(object):
    """------------------------------
    Servicios
    ------------------------------

    """

    def CrearProcessedImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsultarProcessedImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProcessedDatasServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CrearProcessedImage': grpc.unary_unary_rpc_method_handler(
                    servicer.CrearProcessedImage,
                    request_deserializer=processed_datas__pb2.ProcessedImage.FromString,
                    response_serializer=processed_datas__pb2.RespuestaProcessedImage.SerializeToString,
            ),
            'ConsultarProcessedImage': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarProcessedImage,
                    request_deserializer=processed_datas__pb2.QueryProcessedImage.FromString,
                    response_serializer=processed_datas__pb2.RespuestaProcessedImage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'processed_datas.ProcessedDatas', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ProcessedDatas(object):
    """------------------------------
    Servicios
    ------------------------------

    """

    @staticmethod
    def CrearProcessedImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/processed_datas.ProcessedDatas/CrearProcessedImage',
            processed_datas__pb2.ProcessedImage.SerializeToString,
            processed_datas__pb2.RespuestaProcessedImage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConsultarProcessedImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/processed_datas.ProcessedDatas/ConsultarProcessedImage',
            processed_datas__pb2.QueryProcessedImage.SerializeToString,
            processed_datas__pb2.RespuestaProcessedImage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
